# Loading a Client-Side File into Memory

[Getting started with Python integration to SAS速 Viya速 - Part 13 - Loading a Client-Side CSV File into CAS](https://blogs.sas.com/content/sgf/2023/02/07/getting-started-with-python-integration-to-sas-viya-part-13-loading-a-client-side-csv-file-into-cas/) blog post

Downloading data from the SAS Viya Example Data Sets Website: https://support.sas.com/documentation/onlinedoc/viya/examples.htm

In [2]:
## Packages
import swat
import pandas as pd

from casConnect import connect_to_cas ## custom personal module

## Make a Connection to CAS (REQUIRED: MODIFY CONNECTION INFORMATION)

##### To connect to the CAS server you will need:
1. the host name, 
2. the portnumber, 
3. your user name, and your password.

Visit the documentation [Getting Started with SAS速 Viya速 for Python](https://go.documentation.sas.com/doc/en/pgmsascdc/default/caspg3/titlepage.htm) for more information about connecting to CAS.

**Be aware that connecting to the CAS server can be implemented in various ways, so you might need to see your system administrator about how to make a connection. Please follow company policy regarding authentication.**

In [3]:
##
## Connect to CAS
##

## General connection syntax
# conn = swat.CAS(host, port, username, password)

## SAS Viya for Learners 3.5 connection
# hostValue = os.environ.get('CASHOST')
# portValue = os.environ.get('CASPORT')
# passwordToken=os.environ.get('SAS_VIYA_TOKEN')
# conn = swat.CAS(hostname=hostValue, port=portValue, password=passwordToken)

## Personal connection
try:
    conn = connect_to_cas()
    print('CAS connection succesful')
    print(conn)
except:
    print('No connection')
    pass

CAS connection succesful
CAS('ssemonthly.demo.sas.com', 443, protocol='https', name='py-session-1', session='0a22dd6e-dd59-8441-9367-e2381d57af18')

In [4]:
conn.tableInfo(caslib = 'casuser')

NOTE: No tables are available in caslib CASUSER(Peter.Styliadis@sas.com) of Cloud Analytic Services.

+ Elapsed: 0.0105s, user: 0.00631s, sys: 0.0138s, mem: 1.43mb

## Using the Pandas API in the SWAT package (read_csv)

In [5]:
castbl = conn.read_csv(r'https://support.sas.com/documentation/onlinedoc/viya/exampledatasets/heart.csv',
                      casout = {'name':'heart_read_csv', 
                                'caslib':'casuser', 
                                'replace':True})

NOTE: Cloud Analytic Services made the uploaded file available as table HEART_READ_CSV in caslib CASUSER(Peter.Styliadis@sas.com).
NOTE: The table HEART_READ_CSV has been created in caslib CASUSER(Peter.Styliadis@sas.com) from binary data uploaded to Cloud Analytic Services.

In [6]:
conn.tableInfo(caslib = 'casuser')

[TableInfo]

              Name  Rows  Columns  IndexedColumns Encoding        CreateTimeFormatted           ModTimeFormatted        AccessTimeFormatted JavaCharSet    CreateTime       ModTime    AccessTime  Global  Repeated  View  MultiPart SourceName SourceCaslib  Compressed                  Creator Modifier     SourceModTimeFormatted  SourceModTime
 0  HEART_READ_CSV  5209       17               0    utf-8  2023-05-09T18:10:46+00:00  2023-05-09T18:10:46+00:00  2023-05-09T18:10:46+00:00        UTF8  1.999275e+09  1.999275e+09  1.999275e+09       0         0     0          0                                   0  Peter.Styliadis@sas.com           2023-05-09T18:10:46+00:00   1.999275e+09

+ Elapsed: 0.00925s, user: 0.00659s, sys: 0.012s, mem: 1.83mb

In [7]:
display(type(castbl), castbl)

swat.cas.table.CASTable

CASTable('HEART_READ_CSV', caslib='CASUSER(Peter.Styliadis@sas.com)')

In [8]:
castbl.head()

Selected Rows from Table HEART_READ_CSV

  Status DeathCause  AgeCHDdiag     Sex  AgeAtStart  Height  Weight  Diastolic  Systolic    MRW  Smoking  AgeAtDeath  Cholesterol Chol_Status BP_Status Weight_Status   Smoking_Status
0   Dead      Other         NaN  Female        29.0   62.50   140.0       78.0     124.0  121.0      0.0        55.0          NaN                Normal    Overweight       Non-smoker
1   Dead     Cancer         NaN  Female        41.0   59.75   194.0       92.0     144.0  183.0      0.0        57.0        181.0   Desirable      High    Overweight       Non-smoker
2  Alive                    NaN  Female        57.0   62.25   132.0       90.0     170.0  114.0     10.0         NaN        250.0        High      High    Overweight  Moderate (6-15)
3  Alive                    NaN  Female        39.0   65.75   158.0       80.0     128.0  123.0      0.0         NaN        242.0        High    Normal    Overweight       Non-smoker
4  Alive                    NaN    Male        42.0   66.00   156.0       76.0     110.0  116.0     20.0         NaN        281.0        High   Optimal    Overweight    Heavy (16-25)

## Using the upload_file SWAT method

In [9]:
castbl2 = conn.upload_file(r'https://support.sas.com/documentation/onlinedoc/viya/exampledatasets/heart.csv', 
                           casout = {'name':'heart_upload_file', 
                                     'caslib':'casuser',
                                     'replace':True})

NOTE: Cloud Analytic Services made the uploaded file available as table HEART_UPLOAD_FILE in caslib CASUSER(Peter.Styliadis@sas.com).
NOTE: The table HEART_UPLOAD_FILE has been created in caslib CASUSER(Peter.Styliadis@sas.com) from binary data uploaded to Cloud Analytic Services.

In [10]:
conn.tableInfo(caslib = 'casuser')

[TableInfo]

                 Name  Rows  Columns  IndexedColumns Encoding        CreateTimeFormatted           ModTimeFormatted        AccessTimeFormatted JavaCharSet    CreateTime       ModTime    AccessTime  Global  Repeated  View  MultiPart SourceName SourceCaslib  Compressed                  Creator Modifier     SourceModTimeFormatted  SourceModTime
 0     HEART_READ_CSV  5209       17               0    utf-8  2023-05-09T18:10:46+00:00  2023-05-09T18:10:46+00:00  2023-05-09T18:10:47+00:00        UTF8  1.999275e+09  1.999275e+09  1.999275e+09       0         0     0          0                                   0  Peter.Styliadis@sas.com           2023-05-09T18:10:46+00:00   1.999275e+09
 1  HEART_UPLOAD_FILE  5209       17               0    utf-8  2023-05-09T18:10:48+00:00  2023-05-09T18:10:48+00:00  2023-05-09T18:10:48+00:00        UTF8  1.999275e+09  1.999275e+09  1.999275e+09       0         0     0          0                                   0  Peter.Styliadis@sas.com           2023-05-09T18:10:48+00:00   1.999275e+09

+ Elapsed: 0.00892s, user: 0.00223s, sys: 0.0164s, mem: 1.82mb

In [11]:
display(type(castbl2), castbl2)

swat.cas.table.CASTable

CASTable('HEART_UPLOAD_FILE', caslib='CASUSER(Peter.Styliadis@sas.com)')

In [12]:
castbl2.head()

Selected Rows from Table HEART_UPLOAD_FILE

  Status DeathCause  AgeCHDdiag     Sex  AgeAtStart  Height  Weight  Diastolic  Systolic    MRW  Smoking  AgeAtDeath  Cholesterol Chol_Status BP_Status Weight_Status   Smoking_Status
0   Dead      Other         NaN  Female        29.0   62.50   140.0       78.0     124.0  121.0      0.0        55.0          NaN                Normal    Overweight       Non-smoker
1   Dead     Cancer         NaN  Female        41.0   59.75   194.0       92.0     144.0  183.0      0.0        57.0        181.0   Desirable      High    Overweight       Non-smoker
2  Alive                    NaN  Female        57.0   62.25   132.0       90.0     170.0  114.0     10.0         NaN        250.0        High      High    Overweight  Moderate (6-15)
3  Alive                    NaN  Female        39.0   65.75   158.0       80.0     128.0  123.0      0.0         NaN        242.0        High    Normal    Overweight       Non-smoker
4  Alive                    NaN    Male        42.0   66.00   156.0       76.0     110.0  116.0     20.0         NaN        281.0        High   Optimal    Overweight    Heavy (16-25)

## Using the SWAT upload_frame method

In [13]:
## Read the data into a DataFrame
df_raw = pd.read_csv(r'https://support.sas.com/documentation/onlinedoc/viya/exampledatasets/heart.csv')

## Prepare the DataFrame
df = (df_raw
      .rename(columns = lambda colName: colName.upper())
      .assign(
         STATUS = lambda _df: _df.STATUS.str.upper(),
         DEATHCAUSE = lambda _df: _df.DEATHCAUSE.fillna('Still Alive').str.lower()
        )
     .drop('AGEATSTART', axis=1)
)

df.head()

,STATUS,DEATHCAUSE,AGECHDDIAG,SEX,HEIGHT,WEIGHT,DIASTOLIC,SYSTOLIC,MRW,SMOKING,AGEATDEATH,CHOLESTEROL,CHOL_STATUS,BP_STATUS,WEIGHT_STATUS,SMOKING_STATUS
0,DEAD,other,NaN,Female,62.50,140.0,78,124,121.0,0.0,55.0,NaN,NaN,Normal,Overweight,Non-smoker
1,DEAD,cancer,NaN,Female,59.75,194.0,92,144,183.0,0.0,57.0,181.0,Desirable,High,Overweight,Non-smoker
2,ALIVE,still alive,NaN,Female,62.25,132.0,90,170,114.0,10.0,NaN,250.0,High,High,Overweight,Moderate (6-15)
3,ALIVE,still alive,NaN,Female,65.75,158.0,80,128,123.0,0.0,NaN,242.0,High,Normal,Overweight,Non-smoker
4,ALIVE,still alive,NaN,Male,66.00,156.0,76,110,116.0,20.0,NaN,281.0,High,Optimal,Overweight,Heavy (16-25)

In [14]:
castbl3 = conn.upload_frame(df, casout = {'name':'heart_upload_frame', 
                                          'caslib':'casuser', 
                                          'replace':True})

NOTE: Cloud Analytic Services made the uploaded file available as table HEART_UPLOAD_FRAME in caslib CASUSER(Peter.Styliadis@sas.com).
NOTE: The table HEART_UPLOAD_FRAME has been created in caslib CASUSER(Peter.Styliadis@sas.com) from binary data uploaded to Cloud Analytic Services.

In [15]:
conn.tableInfo(caslib = 'casuser')

[TableInfo]

                  Name  Rows  Columns  IndexedColumns Encoding        CreateTimeFormatted           ModTimeFormatted        AccessTimeFormatted JavaCharSet    CreateTime       ModTime    AccessTime  Global  Repeated  View  MultiPart SourceName SourceCaslib  Compressed                  Creator Modifier     SourceModTimeFormatted  SourceModTime
 0      HEART_READ_CSV  5209       17               0    utf-8  2023-05-09T18:10:46+00:00  2023-05-09T18:10:46+00:00  2023-05-09T18:10:47+00:00        UTF8  1.999275e+09  1.999275e+09  1.999275e+09       0         0     0          0                                   0  Peter.Styliadis@sas.com           2023-05-09T18:10:46+00:00   1.999275e+09
 1   HEART_UPLOAD_FILE  5209       17               0    utf-8  2023-05-09T18:10:48+00:00  2023-05-09T18:10:48+00:00  2023-05-09T18:10:49+00:00        UTF8  1.999275e+09  1.999275e+09  1.999275e+09       0         0     0          0                                   0  Peter.Styliadis@sas.com           2023-05-09T18:10:48+00:00   1.999275e+09
 2  HEART_UPLOAD_FRAME  5209       16               0    utf-8  2023-05-09T18:10:50+00:00  2023-05-09T18:10:50+00:00  2023-05-09T18:10:50+00:00        UTF8  1.999275e+09  1.999275e+09  1.999275e+09       0         0     0          0                                   0  Peter.Styliadis@sas.com           2023-05-09T18:10:50+00:00   1.999275e+09

+ Elapsed: 0.00943s, user: 0.00603s, sys: 0.0154s, mem: 1.84mb

## Terminate the CAS connection

In [16]:
conn.terminate()