In [22]:
## Packages
import swat
import os
import pandas as pd
import numpy as np


## custom personal module to connect to my CAS environment
try:
    from casConnect import connect_to_cas 
except:
    print('CasConnect package not available')

    

######################
## Connect to CAS   ##
######################

## My personal connection to CAS. You will need to modify your connection object
try:
    conn = connect_to_cas()
except:
    print('My personal connection to CAS. You will need to modify yours using your connection information.')


## General connection syntax
# conn = swat.CAS(host, port, username, password)

## Viya for Learners 3.5 connection
hostValue = os.environ.get('CASHOST')
portValue = os.environ.get('CASPORT')
passwordToken=os.environ.get('SAS_VIYA_TOKEN')
conn = swat.CAS(hostname=hostValue, port=portValue, password=passwordToken)

CasConnect package not available
My personal connection to CAS. You will need to modify yours using your connection information.

## Create demo CAS tables

In [23]:
def createDemoData(connectionObject):
    '''Specify your CAS connectin object as the parameter'''
    
    connectionObject.loadTable(path = 'RAND_RETAILDEMO.sashdat', caslib = 'samples',
                               casout = {
                                   'caslib':'casuser',
                                   'replace':True
                               })

    myData = {
        'loyalty_id':[0,1],
        'loyalty_value':['No','Yes'],
    }

    df = pd.DataFrame(myData)
    connectionObject.upload_frame(df, 
                                  casout = {
                                        'name':'loyalty_lookup_tbl',
                                        'caslib':'casuser',
                                        'replace':True
                                   })
    
    tableInfo = connectionObject.tableInfo(caslib = 'casuser')
    return tableInfo

createDemoData(conn)

NOTE: Cloud Analytic Services made the file RAND_RETAILDEMO.sashdat available as table RAND_RETAILDEMO in caslib CASUSER(Peter.Styliadis@sas.com).
NOTE: Cloud Analytic Services made the uploaded file available as table LOYALTY_LOOKUP_TBL in caslib CASUSER(Peter.Styliadis@sas.com).
NOTE: The table LOYALTY_LOOKUP_TBL has been created in caslib CASUSER(Peter.Styliadis@sas.com) from binary data uploaded to Cloud Analytic Services.

,Name,Rows,Columns,IndexedColumns,Encoding,CreateTimeFormatted,ModTimeFormatted,AccessTimeFormatted,JavaCharSet,CreateTime,ModTime,AccessTime,Global,Repeated,View,MultiPart,SourceName,SourceCaslib,Compressed,Creator,Modifier,SourceModTimeFormatted,SourceModTime
0,RAND_RETAILDEMO,930046,40,0,utf-8,2023-03-10T08:18:32-05:00,2023-03-10T08:18:32-05:00,2023-03-10T08:18:32-05:00,UTF8,1.994074e+09,1.994074e+09,1.994074e+09,0,0,0,0,RAND_RETAILDEMO.sashdat,Samples,1,Peter.Styliadis@sas.com,,2020-02-19T23:20:56-05:00,1.897792e+09
1,LOYALTY_LOOKUP_TBL,2,2,0,utf-8,2023-03-10T08:18:32-05:00,2023-03-10T08:18:32-05:00,2023-03-10T08:18:32-05:00,UTF8,1.994074e+09,1.994074e+09,1.994074e+09,0,0,0,0,,,0,Peter.Styliadis@sas.com,,2023-03-10T08:18:32-05:00,1.994074e+09
2,LOYALTY_FINAL,930046,5,0,utf-8,2023-03-10T08:12:38-05:00,2023-03-10T08:16:13-05:00,2023-03-10T08:16:13-05:00,UTF8,1.994073e+09,1.994073e+09,1.994073e+09,1,0,0,0,,,0,Peter.Styliadis@sas.com,,,NaN

In [24]:
conn.loadActionSet('fedSQL')

NOTE: Added action set 'fedSQL'.

[actionset]

 'fedSQL'

+ Elapsed: 0.000944s, user: 0.000662s, sys: 0.000269s, mem: 0.239mb

In [25]:
conn.tableInfo(caslib = 'casuser')

,Name,Rows,Columns,IndexedColumns,Encoding,CreateTimeFormatted,ModTimeFormatted,AccessTimeFormatted,JavaCharSet,CreateTime,ModTime,AccessTime,Global,Repeated,View,MultiPart,SourceName,SourceCaslib,Compressed,Creator,Modifier,SourceModTimeFormatted,SourceModTime
0,RAND_RETAILDEMO,930046,40,0,utf-8,2023-03-10T08:18:32-05:00,2023-03-10T08:18:32-05:00,2023-03-10T08:18:32-05:00,UTF8,1.994074e+09,1.994074e+09,1.994074e+09,0,0,0,0,RAND_RETAILDEMO.sashdat,Samples,1,Peter.Styliadis@sas.com,,2020-02-19T23:20:56-05:00,1.897792e+09
1,LOYALTY_LOOKUP_TBL,2,2,0,utf-8,2023-03-10T08:18:32-05:00,2023-03-10T08:18:32-05:00,2023-03-10T08:18:32-05:00,UTF8,1.994074e+09,1.994074e+09,1.994074e+09,0,0,0,0,,,0,Peter.Styliadis@sas.com,,2023-03-10T08:18:32-05:00,1.994074e+09
2,LOYALTY_FINAL,930046,5,0,utf-8,2023-03-10T08:12:38-05:00,2023-03-10T08:16:13-05:00,2023-03-10T08:16:13-05:00,UTF8,1.994073e+09,1.994073e+09,1.994073e+09,1,0,0,0,,,0,Peter.Styliadis@sas.com,,,NaN

### Preview the RAND_RETAILDEMO CAS table

In [26]:
previewRetail = '''
    select *
        from casuser.RAND_RETAILDEMO
        limit 5;
'''
conn.execDirect(query = previewRetail)

,CustID,bucket,age,loyalty_card,Department,brand_name,Storechain,ChannelType,Class,StoreNum,Storeage,trx_hr_char,trx_dow_new,trx_tod,Date,...,Country,Country_Lat,Country_Long,Region,Region_Lat,Region_Long,Region_2,Region_2_Lat,Region_2_Long,State,State_Lat,State_Long,age_bucket,Storechain1,brand_name1
0,1083863.0,1.0,NaN,0.0,health,Pine,GRAND,Resale,oral care,736.0,12.0,2 PM,TUE,Afternoon,2009-12-29,...,United States,41.5435,-74.6941,US_AT,40.3,-74.50,US Atlantic Coast,40.3,-74.50,NY,41.5435,-74.6941,18-25,FAST,Oak
1,1083863.0,1.0,NaN,0.0,kids,Pine,GRAND,Resale,kids_swimwear,736.0,12.0,4 PM,WED,Afternoon,2009-11-11,...,United States,41.5435,-74.6941,US_AT,40.3,-74.50,US Atlantic Coast,40.3,-74.50,NY,41.5435,-74.6941,36-45,GRAND,Pine
2,1083863.0,1.0,NaN,0.0,men,Pine,GRAND,Resale,men_slippers,736.0,12.0,10 AM,THU,Morning,2010-01-28,...,United States,41.2340,-88.3961,US_MW,43.3,-84.75,US Midwest,43.3,-84.75,IL,41.2340,-88.3961,56-65,MODA,Maple
3,1083863.0,2.0,NaN,0.0,men,Pine,GRAND,Internet,men_underwear,724.0,12.0,2 PM,SAT,Afternoon,2009-10-31,...,United States,40.4403,-74.4296,US_AT,40.3,-74.50,US Atlantic Coast,40.3,-74.50,NJ,40.4403,-74.4296,46-55,MODA,Maple
4,1083883.0,2.0,23.0,1.0,electronics,Pine,GRAND,Store,DVD & Blu-ray,757.0,11.0,11 AM,FRI,Morning,2009-09-18,...,United States,38.4575,-96.5830,US_MW,43.3,-84.75,US Midwest,43.3,-84.75,KS,38.4575,-96.5830,26-35,GRAND,Pine

### Preview the LOYALTY_LOOKUP_TBL CAS table

In [27]:
previewLoyalty = '''
    select *
        from casuser.LOYALTY_LOOKUP_TBL
        limit 5;
'''
conn.execDirect(query = previewLoyalty)

[Result Set]

    loyalty_id loyalty_value
 0         0.0            No
 1         1.0           Yes

+ Elapsed: 0.00435s, user: 0.00423s, sys: 9.7e-05s, mem: 3.72mb

## Create a new CAS table using the join

In [41]:
createTable = '''
    create table loyalty_final{options replace=True} as
    select retail.CustID,
           retail.age,
           retail.Department,
           retail.loyalty_card,
           loyalty.loyalty_value
        from casuser.RAND_RETAILDEMO as retail inner join
             casuser.LOYALTY_LOOKUP_TBL as loyalty
        on retail.loyalty_card = loyalty.loyalty_id;
'''

conn.execDirect(query = createTable)

NOTE: Table LOYALTY_FINAL was created in caslib CASUSER(Peter.Styliadis@sas.com) with 930046 rows returned.

+ Elapsed: 0.27s, user: 1.32s, sys: 0.295s, mem: 259mb

### Global column indicates scope

In [42]:
pd.set_option('display.max_columns', 30)

conn.tableInfo(caslib = 'casuser')

,Name,Rows,Columns,IndexedColumns,Encoding,CreateTimeFormatted,ModTimeFormatted,AccessTimeFormatted,JavaCharSet,CreateTime,ModTime,AccessTime,Global,Repeated,View,MultiPart,SourceName,SourceCaslib,Compressed,Creator,Modifier,SourceModTimeFormatted,SourceModTime
0,RAND_RETAILDEMO,930046,40,0,utf-8,2023-03-10T08:18:32-05:00,2023-03-10T08:18:32-05:00,2023-03-10T08:19:38-05:00,UTF8,1.994074e+09,1.994074e+09,1.994074e+09,0,0,0,0,RAND_RETAILDEMO.sashdat,Samples,1,Peter.Styliadis@sas.com,,2020-02-19T23:20:56-05:00,1.897792e+09
1,LOYALTY_LOOKUP_TBL,2,2,0,utf-8,2023-03-10T08:18:32-05:00,2023-03-10T08:18:32-05:00,2023-03-10T08:19:38-05:00,UTF8,1.994074e+09,1.994074e+09,1.994074e+09,0,0,0,0,,,0,Peter.Styliadis@sas.com,,2023-03-10T08:18:32-05:00,1.994074e+09
2,LOYALTY_FINAL,930046,5,0,utf-8,2023-03-10T08:19:38-05:00,2023-03-10T08:19:38-05:00,2023-03-10T08:19:38-05:00,UTF8,1.994074e+09,1.994074e+09,1.994074e+09,0,0,0,0,,,0,Peter.Styliadis@sas.com,,,NaN

### Promote the LOYALTY_FINAL CAS table

In [43]:
loyaltyInfo = conn.CASTable('LOYALTY_FINAL',caslib = 'casuser')

## Specify where you want to proomte it using targetlib. If you don't specify targetlib it'll use the active caslib by default. You can change the promoted table name with table='newtablename'
loyaltyInfo.table.promote(targetlib='casuser')

NOTE: Cloud Analytic Services promoted table LOYALTY_FINAL in caslib CASUSER(Peter.Styliadis@sas.com) to table LOYALTY_FINAL in caslib CASUSER(Peter.Styliadis@sas.com).

+ Elapsed: 0.0121s, user: 0.00147s, sys: 0.0104s, mem: 0.274mb

### Now loyalty_final is promoted (global = 1)

In [44]:
conn.tableInfo(caslib = 'casuser')

,Name,Rows,Columns,IndexedColumns,Encoding,CreateTimeFormatted,ModTimeFormatted,AccessTimeFormatted,JavaCharSet,CreateTime,ModTime,AccessTime,Global,Repeated,View,MultiPart,SourceName,SourceCaslib,Compressed,Creator,Modifier,SourceModTimeFormatted,SourceModTime
0,RAND_RETAILDEMO,930046,40,0,utf-8,2023-03-10T08:18:32-05:00,2023-03-10T08:18:32-05:00,2023-03-10T08:19:38-05:00,UTF8,1.994074e+09,1.994074e+09,1.994074e+09,0,0,0,0,RAND_RETAILDEMO.sashdat,Samples,1,Peter.Styliadis@sas.com,,2020-02-19T23:20:56-05:00,1.897792e+09
1,LOYALTY_LOOKUP_TBL,2,2,0,utf-8,2023-03-10T08:18:32-05:00,2023-03-10T08:18:32-05:00,2023-03-10T08:19:38-05:00,UTF8,1.994074e+09,1.994074e+09,1.994074e+09,0,0,0,0,,,0,Peter.Styliadis@sas.com,,2023-03-10T08:18:32-05:00,1.994074e+09
2,LOYALTY_FINAL,930046,5,0,utf-8,2023-03-10T08:19:38-05:00,2023-03-10T08:19:49-05:00,2023-03-10T08:19:49-05:00,UTF8,1.994074e+09,1.994074e+09,1.994074e+09,1,0,0,0,,,0,Peter.Styliadis@sas.com,,,NaN

## Terminate the CAS session

In [45]:
conn.terminate()